apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: zeda21/flask-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: PYTHONPATH
              value: "/app/src"
            - name: FLASK_APP
              value: "app.py"
            - name: FLASK_ENV
              value: "development"
            - name: FLASK_DEBUG
              value: "1"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST
              value: "database-service"
            - name: POSTGRES_DB
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
spec:
  type: LoadBalancer  # Change from NodePort to LoadBalancer
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 5000    # External port
      targetPort: 5000  # Port on the container
